[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  ROLLUP_DONT_USE_NATIVE = "true"
  NPM_FLAGS = "--legacy-peer-deps"
