[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Prevent Netlify from auto-installing Neon or broken plugins
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
